manifest:
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
    - name: mcutools
      url-base: https://github.com/mcu-tools
    - name: thedjnK
      url-base: https://github.com/thedjnK

  projects:
    - name: zephyr
      remote: zephyr
      revision: main
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - libmetal
          - littlefs
          - mbedtls
          - openamp
          - tinycrypt
          - zcbor
    - name: boards
      remote: thedjnK
      revision: main
    - name: mcuboot
      path: bootloader/mcuboot
      remote: mcutools
      revision: pull/1780/head

  self:
    path: net_loader
